### ISSUE TITLE
Hilarious code needs fixing

### ISSUE THREAD

**Issue by REDitor** [REDitor/mavenfx#1]
I can't figure out how it is not showing while it's running without errors. I know the code is really bad so you are welcome to roast it, but i think it should technically work. Could you please check it out and tell me what is wrong (after the huge laughing episode you will probably get from reading it of course).

**Comment by REDitor** [comment]
I mean the Tic Tac Toe btw. Don't know if the issue is connected to a branch

**Comment by wimmelstein** [comment]
Hi Sander,

Your code is never something to make fun of. That's not what we do. We are here to learn, and you are certainly doing just that.

I can say a lot about this code, but I have a different proposition for you. After my first class I have an hour and thirty minutes free. Why don't we do a refactoring session, the two of us. Others can be free to join if they like. See if we can bounce off ideas and see if we can come to create better code.

We could even do some pair programming. Look that up if you don't know what that is.

Let me know what you think.

Kind regards,
Wim Wiltenburg

**Comment by REDitor** [comment]
Thank you for responding so soon. I think it's a great idea. With first class do you mean on wednessday when we also have the java class or did you mean tomorrow (monday)?

**Comment by wimmelstein** [comment]
No, I only teach on Wednesdays. My first lesson is between 11:00 and 13:15.

**Comment by REDitor** [comment]
okay thats nice because that is with our class. The only thing is I have been sick the past week and still am a little bit, so I will be joining the online class probably. Is it possible to also do that online (if i'm still ill on wednesday)
