### ISSUE TITLE
DarkMode Exercise Stylesheet not working

### ISSUE THREAD

**Issue by REDitor** [REDitor/mavenfx#2]
My program isn't using the stylesheet as expected after doing what is in the slides, could you maybe have a look at what is going wrong? 
(Branch Week5/Lesson2_Exercise/Dark_Mode)

**Comment by wimmelstein** [comment]
I added JMetro, maybe that makes it better. Pull the changes, mvn clean install, and set if you can run it

**Comment by wimmelstein** [comment]
I also pushed a new branch named Week5/stylesheets. Now your custom sheet works, because you were adding the path to the file as "resources/css/style.css". Maven looks for files (configuration, stylesheets, etc.) in the src/main/resources directory. Adding "resources" to the path was overdoing it.

**Comment by REDitor** [comment]
I will take a look today. Thanks for the help
