### ISSUE TITLE
Final Assignment Database usage issue (Just wondering, not incredibly important)

### ISSUE THREAD

**Issue by REDitor** [REDitor/mavenfx#4]
Hi sir,

This is not a major issue because I can just hide the login window and display it again when you logout of the application, but I wanted to be able to actually close it on login and on logout open a new Login window.

I tried to use this code for keeping the database, but when I do the program cannot instantiate the loginwindow (option 1 and 2 both have the same purpose):

![image](https://user-images.githubusercontent.com/71357600/137590782-00bf8810-1886-4779-b163-df8acafb8db5.png)

For the assignment I will just use the hiding of the login window, but I am just really curious on how this does not work and I was hoping you could explain after your holiday.

**Comment by wimmelstein** [comment]
I see what you did there, although I don't like screen shots. They usually don't show the whole problem. But you might want to think aboutt decoupling the login window from the main class.

**Comment by REDitor** [comment]
Okay thank you so much for answering. I get what you are saying and I'll give it a try. Have a nice holiday : )
